project_id = "rcubbmnosawdtaupixnm"

[functions.send-competition-reminders]
verify_jwt = false

[functions.check-registration-deadlines]
verify_jwt = false

[functions.scrape-competitions]
verify_jwt = false

[functions.bootstrap-cron-secret]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.social-notifications]
verify_jwt = false

[functions.watch-competition]
verify_jwt = false
