// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.startsWith('sb_secret_')) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY must be a publishable client key, not a secret key.');
}

const hasSupabaseConfig =
  typeof SUPABASE_URL === 'string' &&
  SUPABASE_URL.length > 0 &&
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

export const isSupabaseConfigured = hasSupabaseConfig;

// The blog and local-first planner must render even when cloud credentials are
// absent (local preview, offline QA, forked deployments). Cloud calls still
// fail explicitly instead of silently talking to an unintended backend.
const SAFE_SUPABASE_URL: string = hasSupabaseConfig ? SUPABASE_URL! : 'https://unconfigured.supabase.co';
const SAFE_SUPABASE_KEY: string = hasSupabaseConfig ? SUPABASE_PUBLISHABLE_KEY! : 'sb_publishable_unconfigured';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_SUPABASE_URL, SAFE_SUPABASE_KEY, {
  global: {
    fetch: hasSupabaseConfig
      ? createSupabaseFetch(SAFE_SUPABASE_KEY)
      : () => Promise.reject(new Error('Supabase is not configured for this deployment.')),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
