const BASE_COURSES = [
  {
    id: "sv_hopp_1_flow_01",
    title: "Hoppklass 1 – Mjukt flow",
    description: "18 passager med tydlig rytm, mjuka riktningsbyten och raka ansatser till långhopp och däck. AgilityManager-original som öppnas direkt i den fulla V2-planeraren.",
    discipline: "Hoppklass",
    level: "Klass 1",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 18,
    focus: ["flow", "grundhandling", "linjer"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "sv_agility_1_balans_01",
    title: "Agilityklass 1 – Balans & flyt",
    description: "18 passager med tunnel, balansbom, slalom, A-hinder och gungbräda placerade för naturliga och raka ansatser. AgilityManager-original i full V2-meterskala.",
    discipline: "Agilityklass",
    level: "Klass 1",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 18,
    focus: ["kontaktfält", "flow", "slalom"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "sv_hopp_2_teknik_01",
    title: "Hoppklass 2 – Teknik & rytm",
    description: "19 passager med tunnel, slalom, däck, långhopp och oxer i ett snabbare men läsbart klass 2-flöde. Regeltestat AgilityManager-original.",
    discipline: "Hoppklass",
    level: "Klass 2",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 19,
    focus: ["teknik", "slalom", "tempoväxling"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "sv_agility_2_handling_01",
    title: "Agilityklass 2 – Handling & kontakt",
    description: "19 passager med tunnlar, balansbom, slalom, A-hinder, gungbräda, oxer och långhopp. Byggd som ett eget klass 2-upplägg för V2-planeraren.",
    discipline: "Agilityklass",
    level: "Klass 2",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 19,
    focus: ["handling", "kontaktfält", "teknik"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "sv_hopp_3_fart_01",
    title: "Hoppklass 3 – Fart & linjeval",
    description: "20 passager med högre fart, däck, tunnel, slalom, oxrar och långhopp med kontrollerade ansatser. AgilityManager-original för avancerad hoppträning.",
    discipline: "Hoppklass",
    level: "Klass 3",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 20,
    focus: ["fart", "linjeval", "avancerad handling"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "sv_agility_3_master_01",
    title: "Agilityklass 3 – Mästerskapsflow",
    description: "20 passager med varierad fart, kontaktfält, slalom, långhopp, tunnlar och oxrar i ett avancerat säkerhetsorienterat flöde.",
    discipline: "Agilityklass",
    level: "Klass 3",
    arenaWidthM: 30,
    arenaHeightM: 40,
    passages: 20,
    focus: ["avancerad handling", "kontaktfält", "fart"],
    isNollklass: false,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_mur_25x30",
    title: "Nollklass Mur/Långhopp – 25×30",
    description: "AgilityManager-original för Nollklass 2026 med 13 passager, vanliga hopp och tunnlar samt långhopp på 25×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 25,
    arenaHeightM: 30,
    passages: 13,
    focus: ["långhopp", "grundhandling", "stor yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_mur_15x30",
    title: "Nollklass Mur/Långhopp – 15×30",
    description: "Kompakt AgilityManager-original för Nollklass 2026 med 13 passager och långhopp på 15×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 15,
    arenaHeightM: 30,
    passages: 13,
    focus: ["långhopp", "grundhandling", "kompakt yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_slalom_25x30",
    title: "Nollklass Slalom – 25×30",
    description: "AgilityManager-original för Nollklass 2026 med 13 passager, tunnlar och ett 12-pinnars slalom på 25×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 25,
    arenaHeightM: 30,
    passages: 13,
    focus: ["slalom", "ingång", "stor yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_slalom_15x30",
    title: "Nollklass Slalom – 15×30",
    description: "Kompakt AgilityManager-original för Nollklass 2026 med 13 passager och ett 12-pinnars slalom på 15×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 15,
    arenaHeightM: 30,
    passages: 13,
    focus: ["slalom", "ingång", "kompakt yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_balans_25x30",
    title: "Nollklass Balans – 25×30",
    description: "AgilityManager-original för Nollklass 2026 med 13 passager, tunnlar och balansbom på 25×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 25,
    arenaHeightM: 30,
    passages: 13,
    focus: ["balansbom", "kontaktfält", "stor yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "noll_2026_balans_15x30",
    title: "Nollklass Balans – 15×30",
    description: "Kompakt AgilityManager-original för Nollklass 2026 med 13 passager och balansbom på 15×30 meters yta. Clear round utan tid.",
    discipline: "Nollklass",
    level: "Nollklass",
    arenaWidthM: 15,
    arenaHeightM: 30,
    passages: 13,
    focus: ["balansbom", "kontaktfält", "kompakt yta"],
    isNollklass: true,
    isHoopers: false,
    mirrorable: true,
  },
  {
    id: "hoopers_1_basic",
    title: "Hoopers startklass – Grund",
    description: "Mjuk Hoopers-bana med hoopar, tunnor och tunnel. Öppnas i samma fulla V2-planerare under Hoopers egen regelprofil.",
    discipline: "Hoopers",
    level: "Startklass",
    arenaWidthM: 30,
    arenaHeightM: 30,
    passages: 10,
    focus: ["grundlinjer", "distans"],
    isNollklass: false,
    isHoopers: true,
    mirrorable: false,
  },
];

function mirrorMeta(course) {
  return {
    ...course,
    id: `${course.id}_mirror`,
    title: `${course.title} · spegel`,
    description: `${course.description} Spegelvänd över banans mittlinje för träning från motsatt handlingssida.`,
    focus: [...course.focus, "spegelträning"],
    isMirror: true,
    sourceId: course.id,
  };
}

export const PUBLIC_COURSE_CATALOG = [
  ...BASE_COURSES.map((course) => ({ ...course, isMirror: false, sourceId: null })),
  ...BASE_COURSES.filter((course) => course.mirrorable).map(mirrorMeta),
].map(({ mirrorable: _mirrorable, ...course }) => course);

export const LEGACY_COURSE_ALIASES = {
  "klass-1-agility-grundflyt": "sv_agility_1_balans_01",
  "klass-1-hopp-flyt": "sv_hopp_1_flow_01",
  "klass-1-agility-kontaktpass": "sv_agility_1_balans_01",
  "klass-2-agility-linjeval": "sv_agility_2_handling_01",
  "klass-2-hopp-tempo": "sv_hopp_2_teknik_01",
  "klass-3-agility-teknik": "sv_agility_3_master_01",
  "klass-3-hopp-teknik": "sv_hopp_3_fart_01",
  "klass-2-agility-tunnelflyt": "sv_agility_2_handling_01",
};

export function resolvePublicCourseId(courseId) {
  if (!courseId) return null;
  return LEGACY_COURSE_ALIASES[courseId] ?? courseId;
}

export function getPublicCourseMeta(courseId) {
  const resolved = resolvePublicCourseId(courseId);
  return PUBLIC_COURSE_CATALOG.find((course) => course.id === resolved);
}
